// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yicsoljqffweqqeafvna.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlpY3NvbGpxZmZ3ZXFxZWFmdm5hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDkyNzAsImV4cCI6MjA3MjgyNTI3MH0.H6irrZjIlAT6-P7F4CPY4tLhtRTw3XUF1DVNNjI5g5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});